extends: semistandard
parserOptions:
  sourceType: script
rules:
  strict:
    - error
    - safe
  max-len:
    - error
    -
      code: 80
      ignoreComments: true
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
